modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="suveren"
version="1.0.0"
displayName="Feudal Sovereign"
description="Srednjeveski kraljestveni mod: krona, zastave, zvesti vitezi, kmetje, orozarne, zitnice in razbojniki."
authors="Feudal Sovereign Team"

[[dependencies.suveren]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.suveren]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
